### ISSUE TITLE
Specified protocol was not requested by the client.

### ISSUE THREAD

**Issue by JonathanWoodward** [zhaojh329/libuwsc#10]
Hello,

I am trying to connect to a nodejs websocket server using libuwsc and I get the error "Specified protocol was not requested by the client." when doing request.accept('echo-protocol', request.origin). 
I understand this to be the protocol set and can not see this in the libuwsc library, am I missing something here?

Many thanks,
J

**Comment by zhaojh329** [comment]
Not implemented.

**Comment by JonathanWoodward** [comment]
Okay, thanks. I removed the protocol and it does work with nodejs websockets.
