### ISSUE TITLE
running example.c gives error

### ISSUE THREAD

**Issue by manibharathytu** [zhaojh329/libuwsc#25]
I did all these steps in order as in README.md successfully.

`sudo apt install libev-dev libssl-dev`

```
git clone --recursive https://github.com/zhaojh329/libuwsc.git
cd libuwsc
mkdir build && cd build
cmake ..
make && sudo make install
```

I'm not able to complile example.c with 
`gcc example.c`

it gives this error 

../example/example.c:30:10: fatal error: uwsc.h: No such file or directory
 #include "uwsc.h"

**Comment by manibharathytu** [comment]
It was a issue with my gcc, compling good with clang

**Comment by abdel8811** [comment]
Hi,
i get this error too, how did you solve it
tanks
