### ISSUE TITLE
明明已经安装了openssl 1.1.1 ，却提示没有安装？

### ISSUE THREAD

**Issue by kvi111** [zhaojh329/libuwsc#4]
在ubuntu18.10下面，明明已经安装了openssl 1.1.1 ，却提示没有安装？

**Comment by zhaojh329** [comment]
apt install libssl-dev

**Comment by kvi111** [comment]
这个没用，我降级安装了openssl1.1.0g，可以了

**Comment by zhaojh329** [comment]
我在Ubuntu-18.04通过apt安装的是1.1.0g，可以的。

**Comment by zhaojh329** [comment]
我又测试了Ubuntu 18.10下，使用apt安装libssl-dev是可以识别的。
root@bb721e43752d:/libuwsc/build# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
root@bb721e43752d:/libuwsc/build# cmake ..
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Libev: /usr/lib/x86_64-linux-gnu/libev.so (found version "4.22") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")  
-- Could NOT find WOLFSSL (missing: WOLFSSL_LIBRARY WOLFSSL_INCLUDE_DIR) 
-- Could NOT find MbedTLS (missing: MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY MBEDTLS_INCLUDE_DIR) 
-- Select OpenSSL as the SSL backend
-- UWSC_VERSION: 3.2.0
-- UWSC_SSL_SUPPORT: OpenSSL
-- Configuring done
-- Generating done
-- Build files have been written to: /libuwsc/build
