### ISSUE TITLE
在多线程下跑，不同的线程使用不同的loop, 发现了个问题

### ISSUE THREAD

**Issue by kvi111** [zhaojh329/libuwsc#5]
提示 libev: a signal must not be attached to two different loops... ,这个应该是libev的问题，大概意思是例子里面的方法 signal_cb 方法只能被一个loop绑定，请问这个问题该怎么解决？ 我就是想通过给线程发sigint信号让线程退出，现在却没法绑定。。。。。。

**Comment by zhaojh329** [comment]
libev可以通过一个watcher给另一个watcher发送事件，可以采用这种方式。可以先研究一下libev。

**Comment by kvi111** [comment]
还有个问题，我想要主动断开websocket连接，怎么处理？
