### ISSUE TITLE
我想要主动断开websocket连接，怎么处理？

### ISSUE THREAD

**Issue by kvi111** [zhaojh329/libuwsc#6]
我想要主动断开websocket连接，怎么处理？

**Comment by zhaojh329** [comment]
哦，目前还没考虑这个问题。没有提供相应接口

**Comment by zhaojh329** [comment]
@kvi111 已经支持了。
https://github.com/zhaojh329/libuwsc/commit/eaacc643025a33b3aacd1ed0f4e81e5ad84cef79
